### ISSUE TITLE
Syntax Error - line 21

### ISSUE THREAD

**Issue by ZakirJaafar** [ze-kel/DayOne-JSON-to-MD#1]
File "app.py", line 21
    nonlocal input
                 
SyntaxError: invalid syntax

**Comment by illkle** [comment]
@ZakirJaafar  You seem to be using python 2, while this script requires python 3.

**Comment by ZakirJaafar** [comment]
Thanks. I got it running $>python app.py when I used python virtual environment. I had python3 installed via brew earlier eventhough the default was running python. I didn't manage to uninstall python 2 in my mac but instead used python virtual environment 
$> python3 -m pip install --user virtualenv
$> python3 -m virtualenv env
$> source env/bin/activate
